Leonardo Zaniboni Silva - 11801049

Repositório referente ao quinto trabalho da disciplina de Desenvolvimento de Software para Sistemas Embarcados com Sistemas Operacionais (SEL0456).

No arquivo main.py, está presente 2 testes. O primeiro deles compara o resultado obtido com o arquivo "output_certo.txt" - que possui as respostas certas. O segundo compara o resultado obtido com o arquivo "output_errado.txt" - que possui alguns erros.

Ao configurar os testes no arquivo "phyton-app.yml", é possível ver que o resultado de cada teste. O primeiro teste rodou sem problemas, conforme esperado. Já o segundo teste deu alguns erros, o que também era esperado, já que os resultados estão sendo comparados com um arquivo que contém erros.

![Captura de tela de 2022-11-16 13-37-22](https://user-images.githubusercontent.com/65432723/202297266-084df8e9-8e94-4097-acd2-8181047bf2fa.png)

Além disso, é possível ver o relatório de erros do segundo teste com as linhas onde estavam localizados os erros (destacado em azul).

![Captura de tela de 2022-11-16 15-34-05](https://user-images.githubusercontent.com/65432723/202300529-22bc289c-2965-4bb9-aac3-d61b46095eb5.png)
